nicedice = require("./nicedice.js");
console.log(nicedice.roll);
console.log(typeof nicedice.roll);
console.log("test");
console.log(nicedice.roll("This is just some text"));
console.log(nicedice.roll("2d6"));
console.log(nicedice.roll("2!6"));
console.log(nicedice.roll("2d"));
console.log(nicedice.roll("d6"));
console.log(nicedice.roll("!6"));
console.log(nicedice.roll("2!"));
console.log(nicedice.roll("!"));
console.log(nicedice.roll("d"));
console.log(nicedice.roll("2d3d6"));
